services:
  recsys-web:
    build:
      context: .
      dockerfile: ./product/bootstrap/web.dockerfile
    depends_on:
      - recsys-kafka
      - recsys-web-backend
    environment:
      KAFKA_HOST: recsys-kafka
      KAFKA_PORT: 9092
      KAFKA_OUT_TOPIC: recsys_out_topic
      KAFKA_OUT_GROUP_ID: recsys-out-group
      KAFKA_AUTO_OFFSET_RESET: earliest
      KAFKA_ENABLE_AUTO_COMMIT: 1
      KAFKA_INITIAL_TIMEOUT: 20
      KAFKA_RETRY_TIMEOUT: 10
    networks:
      - recsys-network
    restart: on-failure

  recsys-web-backend:
    build:
      context: .
      dockerfile: ./product/bootstrap/web_backend.dockerfile
    depends_on:
      - recsys-kafka
      - recsys-llm-api
    environment:
      KAFKA_HOST: recsys-kafka
      KAFKA_PORT: 9092
      KAFKA_REC_TOPIC: recsys_rec_topic
      KAFKA_REC_GROUP_ID: recsys-rec-group
      KAFKA_AUTO_OFFSET_RESET: earliest
      KAFKA_ENABLE_AUTO_COMMIT: 1
      KAFKA_INITIAL_TIMEOUT: 20
      KAFKA_RETRY_TIMEOUT: 10
      POSTGRES_HOST: recsys-database
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '8001:8000' # удалить
    networks:
      - recsys-network
    restart: on-failure
  
  recsys-llm-api:
    build:
      context: .
      dockerfile: ./product/bootstrap/llm_api.dockerfile
    depends_on:
      - recsys-kafka
    environment:
      KAFKA_HOST: recsys-kafka
      KAFKA_PORT: 9092
      KAFKA_LLM_TOPIC: recsys_llm_topic
      KAFKA_LLM_GROUP_ID: recsys-llm-group
      KAFKA_OUT_TOPIC: recsys_out_topic
      KAFKA_OUT_GROUP_ID: recsys-out-group
      KAFKA_AUTO_OFFSET_RESET: earliest
      KAFKA_ENABLE_AUTO_COMMIT: 1
      KAFKA_INITIAL_TIMEOUT: 20
      YANDEX_GPT_FOLDER_ID: ${YANDEX_GPT_FOLDER_ID}
      YANDEX_GPT_API_KEY: ${YANDEX_GPT_API_KEY}
    networks:
      - recsys-network
    restart: on-failure

  recsys-api:
    build:
      context: .
      dockerfile: ./product/bootstrap/recsys_api.dockerfile
    depends_on:
      - recsys-kafka
      - recsys-llm-api
      - recsys-database
    environment:
      KAFKA_HOST: recsys-kafka
      KAFKA_PORT: 9092
      KAFKA_RECSYS_TOPIC: recsys_rec_topic
      KAFKA_RECSYS_GROUP_ID: recsys-rec-group
      KAFKA_OUT_TOPIC: recsys_out_topic
      KAFKA_OUT_GROUP_ID: recsys-out-group
      KAFKA_AUTO_OFFSET_RESET: earliest
      KAFKA_ENABLE_AUTO_COMMIT: 1
      KAFKA_INITIAL_TIMEOUT: 20
      KAFKA_RETRY_TIMEOUT: 10
      POSTGRES_HOST: recsys-database
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/data:ro
      - ./research:/research:ro
    networks:
      - recsys-network
    restart: on-failure

  recsys-kafka:
    image: confluentinc/cp-kafka:7.9.4
    depends_on:
      - recsys-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: recsys-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://recsys-kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'ERROR'
    ports:
      - '9092:9092' # удалить
    networks:
      - recsys-network
    restart: on-failure
    logging:
      driver: 'none'

  recsys-zookeeper:
    image: confluentinc/cp-zookeeper:7.9.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181' # удалить
    networks:
      - recsys-network
    restart: on-failure

    logging:
      driver: 'none'

  recsys-database:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./product/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - recsys-network
    restart: always

volumes:
  postgres_data:

networks:
  recsys-network:
    driver: bridge
